# Generated by Django 6.1.1 on 2026-09-15 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_section_contentblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок блока')),
                ('content', models.TextField(verbose_name='Содержимое (текст/HTML)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blocks/', verbose_name='Изображение')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Порядковый номер внутри раздела')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Блок контента',
                'verbose_name_plural': 'Блоки контента',
                'ordering': ['position'],
            },
        ),
        migrations.DeleteModel(
            name='ButtonColor',
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['position'], 'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.AddField(
            model_name='section',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядковый номер при выводе'),
        ),
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='URL-алиас (slug)'),
        ),
        migrations.AddField(
            model_name='block',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='main.section', verbose_name='Раздел'),
        ),
        migrations.DeleteModel(
            name='ContentBlock',
        ),
    ]
